### ISSUE TITLE
ImportError: cannot import name 'Transformer' from 'pyproj' (C:\Users\nzhuw\Anaconda3\lib\site-packages\pyproj\__init__.py)

### ISSUE THREAD

**Issue by Zhuwaki** [arthurdjn/noiseplanet#1]
I am trying to import the package in my notebook and I get the following error.

![image](https://user-images.githubusercontent.com/60066385/103073888-194ead00-45d1-11eb-8b39-0a788354ee33.png)

ImportError: cannot import name 'Transformer' from 'pyproj' (C:\Users\nzhuw\Anaconda3\lib\site-packages\pyproj\__init__.py)

**Comment by arthurdjn** [comment]
Hi, thanks for reporting this error. I apologize for the delay of my answer, I am working on other projects and I don't have time to maintain everything on my own. All contributors are welcome by the way !
 
This error does not come from ``noiseplanet`` , but from ``pyproj``. I used ``pyproj``version ``2.6.1.post1``. Can you try to download the same version with:

```
pip install pyproj==2.6.1.post1
```

or give me the version of your package with:

```
pip show pyproj
```

so I can try to debug your issue ?

**Comment by Zhuwaki** [comment]
I have installed `pyproj==2.6.1.post1` and it managed to import noiseplanet successfully.

Now implementing the algo. Thank you for the update

**Comment by Limiyang888** [comment]
I have the same problem, but I installed pyproj==2.6.1.post1 which not solve this problem.
ImportError: cannot import name 'Transform' from 'pyproj' (/data1/lmyang/.local/lib/python3.8/site-packages/pyproj/__init__.py)
