### ISSUE TITLE
Incorrect Map Matching Results

### ISSUE THREAD

**Issue by fywu85** [arthurdjn/noiseplanet#3]
I am getting the following result when matching gps with `nearest` method
![image](https://user-images.githubusercontent.com/8881002/123502168-08720900-d5ff-11eb-84e1-b108beeaa76a.png)

To reproduce the above, 
```
import numpy as np
from noiseplanet.matcher import matching
from noiseplanet.ui.foroute import plot_html

track = np.load('track.npy')
np.save('track.npy', track)
graph = matching.model.graph_from_track(track)
track_corr, route_corr, edgeid, stats = matching.match(
    graph, track, method='nearest')
plot_html(
    track, track_corr=track_corr, route_corr=route_corr,
    proj=True, show_graph=True)
```
where `track.npy` is attached in [track.zip](https://github.com/arthurdjn/noiseplanet/files/6719587/track.zip).

**Comment by arthurdjn** [comment]
Hello,
Thank you for your interest in this package, and also the data samples to help me to debug your issue.

It looks like this is not an issue from ``noiseplanet``, but from the graph. The OpenStreetMap is not up to date and a route is missing, thus the algorithm is mapping your track to the nearest **available** route.

![image](https://user-images.githubusercontent.com/48992917/123512924-aa363c00-d679-11eb-98c2-7c994eace78a.png)

**Comment by fywu85** [comment]
Thank you! The proposed fix works.
